name: version_check
description: Check iOS/Android/Mac store version and provide update alert if update is available.
version: 0.5.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/version_check

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  http: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
